// auto generated by VSBootstrapImport.SetupExpected
using System.Collections.Generic;

namespace VSBootstrapImporter.Tests.Services
{
   public static class Files
   {
       public static List<string> Min_Host_CSHtml_File()
       {
            List<string> strings = new List<string>
            {
                 "@page \"/\"",
                 "@namespace Blazor.Pages",
                 "@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers",
                 "@{",
                 "    Layout = null;",
                 "}",
                 "",
                 "<!DOCTYPE html>",
                 "<html lang=\"en\">",
                 "<head>",
                 "    <meta charset=\"utf-8\" />",
                 "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />",
                 "    <title>Blazor</title>",
                 "    <base href=\"~/\" />",
                 "    <link rel=\"stylesheet\" href=\"css/bootstrap/bootstrap.min.css\" />",
                 "    <link href=\"css/site.css\" rel=\"stylesheet\" />",
                 "    @if (Request.Path.Value == \"/Min\")",
                 "    {",
                 "        <link rel=\"stylesheet\" href=\"Min/assets/bootstrap/css/bootstrap.min.css\">",
                 "    }",
                 "</head>",
                 "<body>",
                 "    <app>",
                 "        <component type=\"typeof(App)\" render-mode=\"Static\" />",
                 "    </app>",
                 "",
                 "    <div id=\"blazor-error-ui\">",
                 "        <environment include=\"Staging,Production\">",
                 "            An error has occurred. This application may no longer respond until reloaded.",
                 "        </environment>",
                 "        <environment include=\"Development\">",
                 "            An unhandled exception has occurred. See browser dev tools for details.",
                 "        </environment>",
                 "        <a href=\"\" class=\"reload\">Reload</a>",
                 "        <a class=\"dismiss\">🗙</a>",
                 "    </div>",
                 "",
                 "    <script src=\"_framework/blazor.server.js\"></script>",
                 "    @if(Request.Path.Value == \"/Min\")",
                 "    {",
                 "            <script src=\"Min/assets/js/jquery.min.js\"></script>",
                 "    }",
                 "</body>",
                 "</html>",
            };

            return strings;
       }
       public static List<string> MinNavMenu_Razor_File()
       {
            List<string> strings = new List<string>
            {
                 "<div class=\"top-row pl-4 navbar navbar-dark\">",
                 "    <a class=\"navbar-brand\" href=\"\">Blazor</a>",
                 "    <button class=\"navbar-toggler\" @onclick=\"ToggleNavMenu\">",
                 "        <span class=\"navbar-toggler-icon\"></span>",
                 "    </button>",
                 "</div>",
                 "",
                 "<div class=\"@NavMenuCssClass\" @onclick=\"ToggleNavMenu\">",
                 "    <ul class=\"nav flex-column\">",
                 "        <li class=\"nav-item px-3\">",
                 "            <NavLink class=\"nav-link\" href=\"\" Match=\"NavLinkMatch.All\">",
                 "                <span class=\"oi oi-home\" aria-hidden=\"true\"></span> Home",
                 "            </NavLink>",
                 "        </li>",
                 "        <li class=\"nav-item px-3\">",
                 "            <NavLink class=\"nav-link\" href=\"counter\">",
                 "                <span class=\"oi oi-plus\" aria-hidden=\"true\"></span> Counter",
                 "            </NavLink>",
                 "        </li>",
                 "        <li class=\"nav-item px-3\">",
                 "            <NavLink class=\"nav-link\" href=\"fetchdata\">",
                 "                <span class=\"oi oi-list-rich\" aria-hidden=\"true\"></span> Fetch data",
                 "            </NavLink>",
                 "        </li>",
                 "        <li class=\"nav-item px-3\">",
                 "           <NavLink class=\"nav-link\" href=\"Min\">",
                 "                <span class=\"oi oi-target\" aria-hidden=\"true\"></span> Min",
                 "           </NavLink>",
                 "        </li>",
                 "    </ul>",
                 "</div>",
                 "",
                 "@code {",
                 "    private bool collapseNavMenu = true;",
                 "",
                 "    private string NavMenuCssClass => collapseNavMenu ? \"collapse\" : null;",
                 "",
                 "    private void ToggleNavMenu()",
                 "    {",
                 "        collapseNavMenu = !collapseNavMenu;",
                 "    }",
                 "}",
            };

            return strings;
       }
       public static List<string> MinMin_Razor_File()
       {
            List<string> strings = new List<string>
            {
                 "@page \"/Min\"",
                 "",
                 "    <p>This is a simple test</p><img src=\"Min/assets\\img\\DoleBananas.png\">",
                 "",
                 "@code {",
                 "",
                 "}",
            };

            return strings;
       }
       public static List<string> Min_Wasm_Index_Html_File()
       {
            List<string> strings = new List<string>
            {
                 "<!DOCTYPE html>",
                 "<html>",
                 "",
                 "<head>",
                 "    <meta charset=\"utf-8\" />",
                 "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\" />",
                 "    <title>BlazorWasm</title>",
                 "    <base href=\"/\" />",
                 "    <link href=\"css/bootstrap/bootstrap.min.css\" rel=\"stylesheet\" />",
                 "    <link href=\"css/app.css\" rel=\"stylesheet\" />",
                 "</head>",
                 "",
                 "<body>",
                 "    <app>Loading...</app>",
                 "",
                 "    <div id=\"blazor-error-ui\">",
                 "        An unhandled error has occurred.",
                 "        <a href=\"\" class=\"reload\">Reload</a>",
                 "        <a class=\"dismiss\">🗙</a>",
                 "    </div>",
                 "    <script src=\"_framework/blazor.webassembly.js\"></script>",
                 "    <script src=\"assets/js/jquery.min.js\"></script>",
                 "</body>",
                 "",
                 "</html>",
            };

            return strings;
       }
       public static List<string> Min_Wasm_NavMenu_Razor_File()
       {
            List<string> strings = new List<string>
            {
                 "<div class=\"top-row pl-4 navbar navbar-dark\">",
                 "    <a class=\"navbar-brand\" href=\"\">BlazorWasm</a>",
                 "    <button class=\"navbar-toggler\" @onclick=\"ToggleNavMenu\">",
                 "        <span class=\"navbar-toggler-icon\"></span>",
                 "    </button>",
                 "</div>",
                 "",
                 "<div class=\"@NavMenuCssClass\" @onclick=\"ToggleNavMenu\">",
                 "    <ul class=\"nav flex-column\">",
                 "        <li class=\"nav-item px-3\">",
                 "            <NavLink class=\"nav-link\" href=\"\" Match=\"NavLinkMatch.All\">",
                 "                <span class=\"oi oi-home\" aria-hidden=\"true\"></span> Home",
                 "            </NavLink>",
                 "        </li>",
                 "        <li class=\"nav-item px-3\">",
                 "            <NavLink class=\"nav-link\" href=\"counter\">",
                 "                <span class=\"oi oi-plus\" aria-hidden=\"true\"></span> Counter",
                 "            </NavLink>",
                 "        </li>",
                 "        <li class=\"nav-item px-3\">",
                 "            <NavLink class=\"nav-link\" href=\"fetchdata\">",
                 "                <span class=\"oi oi-list-rich\" aria-hidden=\"true\"></span> Fetch data",
                 "            </NavLink>",
                 "        </li>",
                 "        <li class=\"nav-item px-3\">",
                 "           <NavLink class=\"nav-link\" href=\"Wasm\">",
                 "                <span class=\"oi oi-target\" aria-hidden=\"true\"></span> Wasm",
                 "           </NavLink>",
                 "        </li>",
                 "    </ul>",
                 "</div>",
                 "",
                 "@code {",
                 "    private bool collapseNavMenu = true;",
                 "",
                 "    private string NavMenuCssClass => collapseNavMenu ? \"collapse\" : null;",
                 "",
                 "    private void ToggleNavMenu()",
                 "    {",
                 "        collapseNavMenu = !collapseNavMenu;",
                 "    }",
                 "}",
            };

            return strings;
       }
       public static List<string> Wasm_Razor_File()
       {
            List<string> strings = new List<string>
            {
                 "@page \"/Wasm\"",
                 "",
                 "    <p>This is a simple test</p><img src=\"assets\\img\\DoleBananas.png\">",
                 "",
                 "@code {",
                 "",
                 "}",
            };

            return strings;
       }
       public static List<string> Min_Wasm_PWA_Index_Html_File()
       {
            List<string> strings = new List<string>
            {
                 "<!DOCTYPE html>",
                 "<html>",
                 "",
                 "<head>",
                 "    <meta charset=\"utf-8\" />",
                 "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\" />",
                 "    <title>BlazorWasmPWA</title>",
                 "    <base href=\"/\" />",
                 "    <link href=\"css/bootstrap/bootstrap.min.css\" rel=\"stylesheet\" />",
                 "    <link href=\"css/app.css\" rel=\"stylesheet\" />",
                 "    <link href=\"manifest.json\" rel=\"manifest\" />",
                 "    <link rel=\"apple-touch-icon\" sizes=\"512x512\" href=\"icon-512.png\" />",
                 "</head>",
                 "",
                 "<body>",
                 "    <app>Loading...</app>",
                 "",
                 "    <div id=\"blazor-error-ui\">",
                 "        An unhandled error has occurred.",
                 "        <a href=\"\" class=\"reload\">Reload</a>",
                 "        <a class=\"dismiss\">🗙</a>",
                 "    </div>",
                 "    <script src=\"_framework/blazor.webassembly.js\"></script>",
                 "    <script>navigator.serviceWorker.register('service-worker.js');</script>",
                 "    <script src=\"assets/js/jquery.min.js\"></script>",
                 "</body>",
                 "",
                 "</html>",
            };

            return strings;
       }
       public static List<string> Min_Wasm_PWA_NavMenu_Razor_File()
       {
            List<string> strings = new List<string>
            {
                 "<div class=\"top-row pl-4 navbar navbar-dark\">",
                 "    <a class=\"navbar-brand\" href=\"\">BlazorWasmPWA</a>",
                 "    <button class=\"navbar-toggler\" @onclick=\"ToggleNavMenu\">",
                 "        <span class=\"navbar-toggler-icon\"></span>",
                 "    </button>",
                 "</div>",
                 "",
                 "<div class=\"@NavMenuCssClass\" @onclick=\"ToggleNavMenu\">",
                 "    <ul class=\"nav flex-column\">",
                 "        <li class=\"nav-item px-3\">",
                 "            <NavLink class=\"nav-link\" href=\"\" Match=\"NavLinkMatch.All\">",
                 "                <span class=\"oi oi-home\" aria-hidden=\"true\"></span> Home",
                 "            </NavLink>",
                 "        </li>",
                 "        <li class=\"nav-item px-3\">",
                 "            <NavLink class=\"nav-link\" href=\"counter\">",
                 "                <span class=\"oi oi-plus\" aria-hidden=\"true\"></span> Counter",
                 "            </NavLink>",
                 "        </li>",
                 "        <li class=\"nav-item px-3\">",
                 "            <NavLink class=\"nav-link\" href=\"fetchdata\">",
                 "                <span class=\"oi oi-list-rich\" aria-hidden=\"true\"></span> Fetch data",
                 "            </NavLink>",
                 "        </li>",
                 "        <li class=\"nav-item px-3\">",
                 "           <NavLink class=\"nav-link\" href=\"WasmPWA\">",
                 "                <span class=\"oi oi-target\" aria-hidden=\"true\"></span> WasmPWA",
                 "           </NavLink>",
                 "        </li>",
                 "    </ul>",
                 "</div>",
                 "",
                 "@code {",
                 "    private bool collapseNavMenu = true;",
                 "",
                 "    private string NavMenuCssClass => collapseNavMenu ? \"collapse\" : null;",
                 "",
                 "    private void ToggleNavMenu()",
                 "    {",
                 "        collapseNavMenu = !collapseNavMenu;",
                 "    }",
                 "}",
            };

            return strings;
       }
       public static List<string> Wasm_PWA_Razor_File()
       {
            List<string> strings = new List<string>
            {
                 "@page \"/WasmPWA\"",
                 "",
                 "    <p>This is a simple test</p><img src=\"assets\\img\\DoleBananas.png\">",
                 "",
                 "@code {",
                 "",
                 "}",
            };

            return strings;
       }
       public static List<string> Min_Razor_Layout_CSHtml_File()
       {
            List<string> strings = new List<string>
            {
                 "<!DOCTYPE html>",
                 "<html lang=\"en\">",
                 "<head>",
                 "    <meta charset=\"utf-8\" />",
                 "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />",
                 "    <title>@ViewData[\"Title\"] - Razor</title>",
                 "    <link rel=\"stylesheet\" href=\"~/lib/bootstrap/dist/css/bootstrap.min.css\" />",
                 "    <link rel=\"stylesheet\" href=\"~/css/site.css\" />",
                 "</head>",
                 "<body>",
                 "    <header>",
                 "        <nav class=\"navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3\">",
                 "            <div class=\"container\">",
                 "                <a class=\"navbar-brand\" asp-area=\"\" asp-page=\"/Index\">Razor</a>",
                 "                <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\".navbar-collapse\" aria-controls=\"navbarSupportedContent\"",
                 "                        aria-expanded=\"false\" aria-label=\"Toggle navigation\">",
                 "                    <span class=\"navbar-toggler-icon\"></span>",
                 "                </button>",
                 "                <div class=\"navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse\">",
                 "                    <ul class=\"navbar-nav flex-grow-1\">",
                 "                        <li class=\"nav-item\">",
                 "                            <a class=\"nav-link text-dark\" asp-area=\"\" asp-page=\"/Index\">Home</a>",
                 "                        </li>",
                 "                        <li class=\"nav-item\">",
                 "                            <a class=\"nav-link text-dark\" asp-area=\"\" asp-page=\"/Privacy\">Privacy</a>",
                 "                        </li>",
                 "                <li class=\"nav-item\">",
                 "                    <a class=\"nav-link text-dark\"  asp-area=\"\" asp-page=\"/Razor\">Razor</a>",
                 "                 </li>",
                 "                    </ul>",
                 "                </div>",
                 "            </div>",
                 "        </nav>",
                 "    </header>",
                 "    <div class=\"container\">",
                 "        <main role=\"main\" class=\"pb-3\">",
                 "            @RenderBody()",
                 "        </main>",
                 "    </div>",
                 "",
                 "    <footer class=\"border-top footer text-muted\">",
                 "        <div class=\"container\">",
                 "            &copy; 2020 - Razor - <a asp-area=\"\" asp-page=\"/Privacy\">Privacy</a>",
                 "        </div>",
                 "    </footer>",
                 "",
                 "    <script src=\"~/lib/jquery/dist/jquery.min.js\"></script>",
                 "    <script src=\"~/lib/bootstrap/dist/js/bootstrap.bundle.min.js\"></script>",
                 "    <script src=\"~/js/site.js\" asp-append-version=\"true\"></script>",
                 "",
                 "    @RenderSection(\"Scripts\", required: false)",
                 "</body>",
                 "</html>",
            };

            return strings;
       }
       public static List<string> MIN_Razor_CSHtml_File()
       {
            List<string> strings = new List<string>
            {
                 "@page",
                 "@model RazorModel",
                 "@{",
                 "    ViewData[\"Title\"] = \"Razor\";",
                 "    Layout=\"Razor_Layout.cshtml\";",
                 "",
                 "}",
                 "",
                 "<h1>@ViewData[\"Title\"]</h1>",
                 "",
                 "    <p>This is a simple test</p><img src=\"Razor/assets\\img\\DoleBananas.png\">",
                 "",
            };

            return strings;
       }
       public static List<string> MIN_Razor_CSHtml_CS_File()
       {
            List<string> strings = new List<string>
            {
                 "using System;",
                 "using System.Collections.Generic;",
                 "using System.Linq;",
                 "using System.Threading.Tasks;",
                 "using Microsoft.AspNetCore.Mvc;",
                 "using Microsoft.AspNetCore.Mvc.RazorPages;",
                 "using Microsoft.Extensions.Logging;",
                 "",
                 "namespace ",
                 "{",
                 "   public class RazorModel : PageModel",
                 "   {",
                 "        private readonly ILogger<RazorModel> _logger;",
                 "",
                 "        public RazorModel(ILogger<RazorModel> logger)",
                 "        {",
                 "            _logger = logger;",
                 "        }",
                 "",
                 "        public void OnGet()",
                 "        {",
                 "",
                 "        }",
                 "    }",
                 "}",
                 "",
            };

            return strings;
       }
       public static List<string> MIN_Razor_Razor_Layout_CSHtml_File()
       {
            List<string> strings = new List<string>
            {
                 "<!DOCTYPE html>",
                 "<html lang=\"en\">",
                 "<head>",
                 "    <meta charset=\"utf-8\" />",
                 "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />",
                 "    <title>@ViewData[\"Title\"] - Razor</title>",
                 "    <link rel=\"stylesheet\" href=\"~/lib/bootstrap/dist/css/bootstrap.min.css\" />",
                 "    <link rel=\"stylesheet\" href=\"~/css/site.css\" />",
                 "        <link rel=\"stylesheet\" href=\"Razor/assets/bootstrap/css/bootstrap.min.css\">",
                 "</head>",
                 "<body>",
                 "    <header>",
                 "        <nav class=\"navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3\">",
                 "            <div class=\"container\">",
                 "                <a class=\"navbar-brand\" asp-area=\"\" asp-page=\"/Index\">Razor</a>",
                 "                <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\".navbar-collapse\" aria-controls=\"navbarSupportedContent\"",
                 "                        aria-expanded=\"false\" aria-label=\"Toggle navigation\">",
                 "                    <span class=\"navbar-toggler-icon\"></span>",
                 "                </button>",
                 "                <div class=\"navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse\">",
                 "                    <ul class=\"navbar-nav flex-grow-1\">",
                 "                        <li class=\"nav-item\">",
                 "                            <a class=\"nav-link text-dark\" asp-area=\"\" asp-page=\"/Index\">Home</a>",
                 "                        </li>",
                 "                        <li class=\"nav-item\">",
                 "                            <a class=\"nav-link text-dark\" asp-area=\"\" asp-page=\"/Privacy\">Privacy</a>",
                 "                        </li>",
                 "                <li class=\"nav-item\">",
                 "                    <a class=\"nav-link text-dark\"  asp-area=\"\" asp-page=\"/Razor\">Razor</a>",
                 "                 </li>",
                 "                    </ul>",
                 "                </div>",
                 "            </div>",
                 "        </nav>",
                 "    </header>",
                 "    <div class=\"container\">",
                 "        <main role=\"main\" class=\"pb-3\">",
                 "            @RenderBody()",
                 "        </main>",
                 "    </div>",
                 "",
                 "    <footer class=\"border-top footer text-muted\">",
                 "        <div class=\"container\">",
                 "            &copy; 2020 - Razor - <a asp-area=\"\" asp-page=\"/Privacy\">Privacy</a>",
                 "        </div>",
                 "    </footer>",
                 "",
                 "    <script src=\"~/lib/jquery/dist/jquery.min.js\"></script>",
                 "    <script src=\"~/lib/bootstrap/dist/js/bootstrap.bundle.min.js\"></script>",
                 "    <script src=\"~/js/site.js\" asp-append-version=\"true\"></script>",
                 "",
                 "    @RenderSection(\"Scripts\", required: false)",
                 "    <script src=\"Razor/assets/js/jquery.min.js\"></script>",
                 "</body>",
                 "</html>",
            };

            return strings;
       }
       public static List<string> MIN_Razor_Layout_CSHtml_File()
       {
            List<string> strings = new List<string>
            {
                 "<!DOCTYPE html>",
                 "<html lang=\"en\">",
                 "<head>",
                 "    <meta charset=\"utf-8\" />",
                 "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />",
                 "    <title>@ViewData[\"Title\"] - Razor</title>",
                 "    <link rel=\"stylesheet\" href=\"~/lib/bootstrap/dist/css/bootstrap.min.css\" />",
                 "    <link rel=\"stylesheet\" href=\"~/css/site.css\" />",
                 "</head>",
                 "<body>",
                 "    <header>",
                 "        <nav class=\"navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3\">",
                 "            <div class=\"container\">",
                 "                <a class=\"navbar-brand\" asp-area=\"\" asp-page=\"/Index\">Razor</a>",
                 "                <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\".navbar-collapse\" aria-controls=\"navbarSupportedContent\"",
                 "                        aria-expanded=\"false\" aria-label=\"Toggle navigation\">",
                 "                    <span class=\"navbar-toggler-icon\"></span>",
                 "                </button>",
                 "                <div class=\"navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse\">",
                 "                    <ul class=\"navbar-nav flex-grow-1\">",
                 "                        <li class=\"nav-item\">",
                 "                            <a class=\"nav-link text-dark\" asp-area=\"\" asp-page=\"/Index\">Home</a>",
                 "                        </li>",
                 "                        <li class=\"nav-item\">",
                 "                            <a class=\"nav-link text-dark\" asp-area=\"\" asp-page=\"/Privacy\">Privacy</a>",
                 "                        </li>",
                 "                <li class=\"nav-item\">",
                 "                    <a class=\"nav-link text-dark\"  asp-area=\"\" asp-page=\"/Razor\">Razor</a>",
                 "                 </li>",
                 "                    </ul>",
                 "                </div>",
                 "            </div>",
                 "        </nav>",
                 "    </header>",
                 "    <div class=\"container\">",
                 "        <main role=\"main\" class=\"pb-3\">",
                 "            @RenderBody()",
                 "        </main>",
                 "    </div>",
                 "",
                 "    <footer class=\"border-top footer text-muted\">",
                 "        <div class=\"container\">",
                 "            &copy; 2020 - Razor - <a asp-area=\"\" asp-page=\"/Privacy\">Privacy</a>",
                 "        </div>",
                 "    </footer>",
                 "",
                 "    <script src=\"~/lib/jquery/dist/jquery.min.js\"></script>",
                 "    <script src=\"~/lib/bootstrap/dist/js/bootstrap.bundle.min.js\"></script>",
                 "    <script src=\"~/js/site.js\" asp-append-version=\"true\"></script>",
                 "",
                 "    @RenderSection(\"Scripts\", required: false)",
                 "</body>",
                 "</html>",
            };

            return strings;
       }
   }
}

